import type { FormSchema } from '@/types/form-schema.types';

export const proofOfFundsSchema: FormSchema = {
  id: 'proof-of-funds',
  version: 2,
  title: 'Loan Application Form',
  description: 'Complete this form to apply for a proof of funds loan',
  validation: {
    validateOnBlur: true,
    validateOnChange: false,
    showErrorsOnSubmit: true,
  },
  steps: [
    // Step 1: Applicant Type & Loan Purpose
    {
      id: 'applicant-type',
      title: 'Applicant Type & Purpose',
      description: 'Select your applicant category and the purpose of your loan',
      fields: [
        {
          id: 'applicantCategory',
          name: 'applicant.category',
          type: 'radio',
          label: 'Applicant Category',
          required: true,
          options: [
            {
              value: 'individual',
              label: 'Individual',
              description: 'Apply as an individual borrower',
            },
            {
              value: 'individual_corporate',
              label: 'Individual + Corporate (Joint & Several)',
              description: 'Apply as individual with corporate entity as co-borrower',
            },
          ],
          templateVariable: 'applicant_type',
        },
        {
          id: 'loanPurpose',
          name: 'loan.purpose',
          type: 'icon-select',
          label: 'Primary Purpose of Loan',
          required: true,
          options: [
            {
              value: 'visa_pof',
              label: 'Visa-Related Proof of Funds',
              description: 'For student, visitor, or work visa applications',
              icon: 'passport',
            },
            {
              value: 'lpo_financing',
              label: 'Local Purchase Order (LPO) Financing',
              description: 'Financing for government or private contracts',
              icon: 'file-text',
            },
            {
              value: 'working_capital',
              label: 'Working Capital Support',
              description: 'Short-term business financing needs',
              icon: 'trending-up',
            },
            {
              value: 'bridge_facility',
              label: 'Temporary Fund Placement / Bridge Facility',
              description: 'Short-term bridging finance',
              icon: 'git-branch',
            },
            {
              value: 'other',
              label: 'Other',
              description: 'Specify your purpose',
              icon: 'more-horizontal',
            },
          ],
          templateVariable: 'loan_purpose',
        },
        {
          id: 'otherPurposeDescription',
          name: 'loan.otherPurposeDescription',
          type: 'text',
          label: 'Specify Purpose',
          placeholder: 'Describe the purpose of your loan',
          required: true,
          showIf: {
            field: 'loan.purpose',
            operator: 'equals',
            value: 'other',
          },
          templateVariable: 'other_purpose',
        },
      ],
    },

    // Step 2: Visa Category (shown if purpose is visa_pof)
    {
      id: 'visa-category',
      title: 'Visa Category',
      description: 'Select the type of visa you are applying for',
      showIf: {
        field: 'loan.purpose',
        operator: 'equals',
        value: 'visa_pof',
      },
      fields: [
        {
          id: 'visaType',
          name: 'visa.type',
          type: 'radio',
          label: 'Visa Type',
          required: true,
          options: [
            {
              value: 'student',
              label: 'Student Visa',
              description: 'For studying abroad at a university or college',
            },
            {
              value: 'visiting',
              label: 'Visiting / Tourist Visa',
              description: 'For tourism, family visits, or short stays',
            },
            {
              value: 'skilled_work',
              label: 'Skilled Work / Employment Visa',
              description: 'For employment or skilled worker programs',
            },
          ],
          templateVariable: 'visa_type',
        },
        {
          id: 'visaCountry',
          name: 'visa.country',
          type: 'country',
          label: 'Country of Application',
          required: true,
          templateVariable: 'destination_country',
        },
      ],
    },

    // Step 3A: Student Visa Details
    {
      id: 'student-visa-details',
      title: 'Student Visa Details',
      description: 'Provide details about the student and institution',
      showIf: {
        field: 'visa.type',
        operator: 'equals',
        value: 'student',
      },
      fields: [
        {
          id: 'studentFullName',
          name: 'student.fullName',
          type: 'text',
          label: 'Student Full Name',
          placeholder: 'Enter student full name as on passport',
          required: true,
          templateVariable: 'student_name',
        },
        {
          id: 'studentRelationship',
          name: 'student.relationshipToBorrower',
          type: 'select',
          label: 'Relationship to Borrower(s)',
          required: true,
          options: [
            { value: 'self', label: 'Self' },
            { value: 'son', label: 'Son' },
            { value: 'daughter', label: 'Daughter' },
            { value: 'spouse', label: 'Spouse' },
            { value: 'sibling', label: 'Sibling' },
            { value: 'other', label: 'Other' },
          ],
          templateVariable: 'student_relationship',
        },
        {
          id: 'institutionName',
          name: 'student.institutionName',
          type: 'text',
          label: 'Institution Name',
          placeholder: 'e.g., University of Toronto',
          required: true,
          templateVariable: 'institution_name',
        },
        {
          id: 'programme',
          name: 'student.programme',
          type: 'text',
          label: 'Programme of Study',
          placeholder: 'e.g., Bachelor of Computer Science',
          required: true,
          templateVariable: 'programme',
        },
        {
          id: 'session',
          name: 'student.session',
          type: 'text',
          label: 'Session / Intake',
          placeholder: 'e.g., 2025/2026',
          required: true,
          templateVariable: 'session',
        },
        {
          id: 'studyMode',
          name: 'student.studyMode',
          type: 'radio',
          label: 'Study Mode',
          required: true,
          options: [
            { value: 'full_time', label: 'Full-Time' },
            { value: 'part_time', label: 'Part-Time' },
          ],
          templateVariable: 'study_mode',
        },
        {
          id: 'studentId',
          name: 'student.studentId',
          type: 'text',
          label: 'Student ID (if issued)',
          placeholder: 'Enter student ID from admission letter',
          templateVariable: 'student_id',
        },
        {
          id: 'startDate',
          name: 'student.startDate',
          type: 'date',
          label: 'Expected Start Date of Programme',
          required: true,
          templateVariable: 'programme_start_date',
        },
        {
          id: 'campusLocation',
          name: 'student.campusLocation',
          type: 'text',
          label: 'Campus Location (City)',
          placeholder: 'e.g., Toronto, Ontario',
          templateVariable: 'campus_city',
        },
      ],
    },

    // Step 3B: Visiting Visa Details
    {
      id: 'visiting-visa-details',
      title: 'Visiting Visa Details',
      description: 'Provide details about your visit',
      showIf: {
        field: 'visa.type',
        operator: 'equals',
        value: 'visiting',
      },
      fields: [
        {
          id: 'visitorName',
          name: 'visiting.applicantName',
          type: 'text',
          label: 'Applicant Full Name',
          placeholder: 'Enter full name as on passport',
          required: true,
          templateVariable: 'visitor_name',
        },
        {
          id: 'visitPurpose',
          name: 'visiting.purpose',
          type: 'text',
          label: 'Purpose of Visit',
          placeholder: 'e.g., Tourism, Family Visit, Business',
          required: true,
          templateVariable: 'visit_purpose',
        },
        {
          id: 'durationOfStay',
          name: 'visiting.durationDays',
          type: 'number',
          label: 'Duration of Stay (days)',
          placeholder: 'e.g., 30',
          required: true,
          templateVariable: 'stay_duration',
        },
        {
          id: 'hostDetails',
          name: 'visiting.hostDetails',
          type: 'textarea',
          label: 'Host / Hotel Details (optional)',
          placeholder: 'Enter accommodation or host details',
          rows: 3,
          templateVariable: 'host_details',
        },
      ],
    },

    // Step 3C: Skilled Work Visa Details
    {
      id: 'work-visa-details',
      title: 'Skilled Work Visa Details',
      description: 'Provide details about your employment',
      showIf: {
        field: 'visa.type',
        operator: 'equals',
        value: 'skilled_work',
      },
      fields: [
        {
          id: 'workerName',
          name: 'work.applicantName',
          type: 'text',
          label: 'Applicant Full Name',
          placeholder: 'Enter full name as on passport',
          required: true,
          templateVariable: 'worker_name',
        },
        {
          id: 'employerName',
          name: 'work.employerName',
          type: 'text',
          label: 'Employer Name',
          placeholder: 'e.g., ABC Corporation Ltd',
          required: true,
          templateVariable: 'employer_name',
        },
        {
          id: 'jobTitle',
          name: 'work.jobTitle',
          type: 'text',
          label: 'Job Title / Role',
          placeholder: 'e.g., Software Engineer',
          required: true,
          templateVariable: 'job_title',
        },
        {
          id: 'contractDuration',
          name: 'work.contractDuration',
          type: 'text',
          label: 'Contract Duration',
          placeholder: 'e.g., 2 years',
          templateVariable: 'contract_duration',
        },
        {
          id: 'contractStart',
          name: 'work.contractStartDate',
          type: 'date',
          label: 'Contract Start Date',
          templateVariable: 'work_start_date',
        },
      ],
    },

    // Step 4: LPO / Contract Details (shown if purpose is lpo_financing)
    {
      id: 'lpo-details',
      title: 'LPO & Contract Details',
      description: 'Provide details about your contract or local purchase order',
      showIf: {
        field: 'loan.purpose',
        operator: 'equals',
        value: 'lpo_financing',
      },
      fields: [
        {
          id: 'contractType',
          name: 'lpo.contractType',
          type: 'radio',
          label: 'Contract Type',
          required: true,
          options: [
            { value: 'government', label: 'Government' },
            { value: 'private', label: 'Private Company' },
            { value: 'ngo', label: 'NGO / International Organisation' },
          ],
          templateVariable: 'contract_type',
        },
        {
          id: 'contractingEntity',
          name: 'lpo.contractingEntity',
          type: 'text',
          label: 'Contracting Entity Name',
          placeholder: 'e.g., Ministry of Works',
          required: true,
          templateVariable: 'contracting_entity',
        },
        {
          id: 'lpoReference',
          name: 'lpo.referenceNumber',
          type: 'text',
          label: 'Contract Reference / LPO Number',
          placeholder: 'Enter contract or LPO reference number',
          required: true,
          templateVariable: 'lpo_reference',
        },
        {
          id: 'goodsServices',
          name: 'lpo.goodsServices',
          type: 'textarea',
          label: 'Nature of Goods / Services',
          placeholder: 'Describe the goods or services being supplied',
          required: true,
          rows: 3,
          templateVariable: 'goods_services_description',
        },
        {
          id: 'contractValue',
          name: 'lpo.contractValue',
          type: 'currency',
          label: 'Contract Value',
          placeholder: 'Enter contract value',
          required: true,
          templateVariable: 'contract_value',
        },
        {
          id: 'lpoContractDuration',
          name: 'lpo.duration',
          type: 'text',
          label: 'Contract Duration',
          placeholder: 'e.g., 6 months',
          templateVariable: 'contract_duration',
        },
        {
          id: 'expectedPaymentDate',
          name: 'lpo.expectedPaymentDate',
          type: 'date',
          label: 'Expected Payment Date from Client',
          required: true,
          templateVariable: 'client_payment_date',
        },
      ],
    },

    // Step 5: Working Capital Details (shown if purpose is working_capital)
    {
      id: 'working-capital-details',
      title: 'Working Capital Details',
      description: 'Provide details about your business and funding needs',
      showIf: {
        field: 'loan.purpose',
        operator: 'equals',
        value: 'working_capital',
      },
      fields: [
        {
          id: 'businessName',
          name: 'workingCapital.businessName',
          type: 'text',
          label: 'Business Name',
          placeholder: 'Enter your registered business name',
          required: true,
          templateVariable: 'business_name',
        },
        {
          id: 'businessNature',
          name: 'workingCapital.natureOfBusiness',
          type: 'text',
          label: 'Nature of Business',
          placeholder: 'e.g., Retail, Manufacturing, Services',
          required: true,
          templateVariable: 'business_nature',
        },
        {
          id: 'useOfFunds',
          name: 'workingCapital.useOfFunds',
          type: 'checkbox-group',
          label: 'Use of Funds (Select all that apply)',
          required: true,
          options: [
            { value: 'inventory', label: 'Inventory' },
            { value: 'payroll', label: 'Payroll' },
            { value: 'operations', label: 'Operations' },
            { value: 'short_term_obligations', label: 'Short-term Obligations' },
            { value: 'other', label: 'Other' },
          ],
          templateVariable: 'funds_usage',
        },
        {
          id: 'otherUseDescription',
          name: 'workingCapital.otherUseDescription',
          type: 'text',
          label: 'Specify Other Use',
          placeholder: 'Describe the other use of funds',
          showIf: {
            field: 'workingCapital.useOfFunds',
            operator: 'contains',
            value: 'other',
          },
        },
        {
          id: 'cashInflowSource',
          name: 'workingCapital.cashInflowSource',
          type: 'text',
          label: 'Expected Cash Inflow Source',
          placeholder: 'e.g., Sales revenue, Contract payment',
          required: true,
          templateVariable: 'repayment_source',
        },
        {
          id: 'estimatedRepayment',
          name: 'workingCapital.estimatedRepaymentDate',
          type: 'date',
          label: 'Estimated Repayment Date',
          required: true,
          templateVariable: 'estimated_repayment_date',
        },
      ],
    },

    // Step 6: Borrower Details
    {
      id: 'borrower-details',
      title: 'Borrower Information',
      description: 'Provide details about the individual borrower(s)',
      fields: [
        {
          id: 'borrowerName',
          name: 'borrower.fullName',
          type: 'text',
          label: 'Borrower Full Name',
          placeholder: 'Enter full legal name',
          required: true,
          templateVariable: 'borrower_name',
        },
        {
          id: 'borrowerAddress',
          name: 'borrower.address',
          type: 'textarea',
          label: 'Residential Address',
          placeholder: 'Enter your complete residential address',
          required: true,
          rows: 2,
          templateVariable: 'borrower_address',
        },
        {
          id: 'borrowerPassport',
          name: 'borrower.passportNumber',
          type: 'text',
          label: 'International Passport Number',
          placeholder: 'e.g., A12345678',
          required: true,
          templateVariable: 'borrower_passport',
        },
        {
          id: 'borrowerNIN',
          name: 'borrower.nin',
          type: 'text',
          label: 'NIN (National Identification Number)',
          placeholder: 'Enter your 11-digit NIN',
          required: true,
          validation: {
            pattern: '^[0-9]{11}$',
            patternMessage: 'NIN must be exactly 11 digits',
          },
          templateVariable: 'borrower_nin',
        },
        {
          id: 'borrowerPhone',
          name: 'borrower.phone',
          type: 'phone',
          label: 'Mobile Number',
          placeholder: '08012345678',
          required: true,
          templateVariable: 'borrower_phone',
        },
        {
          id: 'borrowerEmail',
          name: 'borrower.email',
          type: 'email',
          label: 'Email Address',
          placeholder: 'yourname@email.com',
          templateVariable: 'borrower_email',
        },
      ],
    },

    // Step 7: Corporate Borrower (shown if applicant category is individual_corporate)
    {
      id: 'corporate-borrower',
      title: 'Corporate Borrower Details',
      description: 'Provide details about the corporate co-borrower',
      showIf: {
        field: 'applicant.category',
        operator: 'equals',
        value: 'individual_corporate',
      },
      fields: [
        {
          id: 'companyHoldsFunds',
          name: 'corporate.holdsFunds',
          type: 'checkbox',
          label: 'Funds will be held in a Corporate Account',
        },
        {
          id: 'companyName',
          name: 'corporate.companyName',
          type: 'text',
          label: 'Company Name',
          placeholder: 'Enter registered company name',
          required: true,
          templateVariable: 'company_name',
        },
        {
          id: 'companyRcNumber',
          name: 'corporate.rcNumber',
          type: 'text',
          label: 'RC Number',
          placeholder: 'e.g., RC123456',
          required: true,
          templateVariable: 'company_rc_number',
        },
        {
          id: 'companyAddress',
          name: 'corporate.address',
          type: 'textarea',
          label: 'Company Address',
          placeholder: 'Enter registered company address',
          required: true,
          rows: 2,
          templateVariable: 'company_address',
        },
        {
          id: 'companyBank',
          name: 'corporate.bankName',
          type: 'text',
          label: 'Company Bank Name',
          placeholder: 'e.g., First Bank',
          required: true,
          templateVariable: 'company_bank',
        },
        {
          id: 'companyAccountNumber',
          name: 'corporate.accountNumber',
          type: 'text',
          label: 'Company Account Number',
          placeholder: 'Enter 10-digit account number',
          required: true,
          validation: {
            pattern: '^[0-9]{10}$',
            patternMessage: 'Account number must be exactly 10 digits',
          },
          templateVariable: 'company_account',
        },
        {
          id: 'companyRelationship',
          name: 'corporate.relationshipToBorrower',
          type: 'text',
          label: 'Relationship to Individual Borrower(s)',
          placeholder: 'e.g., Director, Shareholder',
          required: true,
          templateVariable: 'company_relationship',
        },
      ],
    },

    // Step 8: Agent Details
    {
      id: 'agent-details',
      title: 'Agent Details',
      description: 'Provide details about the facilitating agent',
      fields: [
        {
          id: 'agentName',
          name: 'agent.fullName',
          type: 'text',
          label: 'Agent Full Name',
          placeholder: 'Enter agent full name',
          required: true,
          templateVariable: 'agent_name',
        },
        {
          id: 'agentAddress',
          name: 'agent.address',
          type: 'textarea',
          label: 'Agent Address',
          placeholder: 'Enter agent address',
          required: true,
          rows: 2,
          templateVariable: 'agent_address',
        },
        {
          id: 'agentNIN',
          name: 'agent.nin',
          type: 'text',
          label: 'Agent NIN',
          placeholder: 'Enter 11-digit NIN',
          required: true,
          validation: {
            pattern: '^[0-9]{11}$',
            patternMessage: 'NIN must be exactly 11 digits',
          },
          templateVariable: 'agent_nin',
        },
        {
          id: 'agentPhone',
          name: 'agent.phone',
          type: 'phone',
          label: 'Agent Mobile Number',
          placeholder: '08012345678',
          required: true,
          templateVariable: 'agent_phone',
        },
        {
          id: 'agentEmail',
          name: 'agent.email',
          type: 'email',
          label: 'Agent Email Address',
          placeholder: 'agent@email.com',
          templateVariable: 'agent_email',
        },
      ],
    },

    // Step 9: Loan Amount & Disbursement
    {
      id: 'loan-amount',
      title: 'Loan Amount & Disbursement',
      description: 'Specify the loan amount and disbursement details',
      fields: [
        {
          id: 'loanAmount',
          name: 'loan.amount',
          type: 'currency',
          label: 'Loan Amount',
          placeholder: 'Enter loan amount',
          required: true,
          helpText: 'Enter the total amount you wish to borrow',
          validation: {
            min: 1000000,
          },
          templateVariable: 'loan_amount',
        },
        {
          id: 'loanAmountWords',
          name: 'loan.amountInWords',
          type: 'text',
          label: 'Amount in Words',
          placeholder: 'e.g., Seven Million Naira only',
          required: true,
          helpText: 'Write out the amount in words',
          templateVariable: 'loan_amount_words',
        },
        {
          id: 'disbursementBank',
          name: 'disbursement.bankName',
          type: 'text',
          label: 'Disbursement Bank Name',
          placeholder: 'e.g., First Bank',
          required: true,
          templateVariable: 'disbursement_bank',
        },
        {
          id: 'disbursementAccountName',
          name: 'disbursement.accountName',
          type: 'text',
          label: 'Disbursement Account Name',
          placeholder: 'Account holder name',
          required: true,
          templateVariable: 'disbursement_account_name',
        },
        {
          id: 'disbursementAccountNumber',
          name: 'disbursement.accountNumber',
          type: 'text',
          label: 'Disbursement Account Number',
          placeholder: 'Enter 10-digit account number',
          required: true,
          validation: {
            pattern: '^[0-9]{10}$',
            patternMessage: 'Account number must be exactly 10 digits',
          },
          templateVariable: 'disbursement_account_number',
        },
      ],
    },

    // Step 10: Loan Duration & Repayment
    {
      id: 'loan-duration',
      title: 'Loan Duration & Repayment',
      description: 'Specify the loan duration and repayment terms',
      fields: [
        {
          id: 'loanStartDate',
          name: 'loan.startDate',
          type: 'date',
          label: 'Loan Start Date',
          required: true,
          templateVariable: 'loan_start_date',
        },
        {
          id: 'loanEndDate',
          name: 'loan.endDate',
          type: 'date',
          label: 'Loan End Date',
          required: true,
          templateVariable: 'loan_end_date',
        },
        {
          id: 'repaymentMethod',
          name: 'repayment.method',
          type: 'radio',
          label: 'Repayment Method',
          required: true,
          options: [
            {
              value: 'lump_sum',
              label: 'Lump Sum',
              description: 'Single payment at end of term',
            },
            {
              value: 'bullet',
              label: 'Bullet Payment',
              description: 'Principal at maturity with periodic interest',
            },
          ],
          templateVariable: 'repayment_method',
        },
        {
          id: 'repaymentDate',
          name: 'repayment.date',
          type: 'date',
          label: 'Repayment Date',
          required: true,
          templateVariable: 'repayment_date',
        },
        {
          id: 'repaymentBank',
          name: 'repayment.bankName',
          type: 'text',
          label: 'Repayment Bank Name',
          placeholder: 'Bank to receive repayment',
          required: true,
          templateVariable: 'repayment_bank',
        },
        {
          id: 'repaymentAccountName',
          name: 'repayment.accountName',
          type: 'text',
          label: 'Repayment Account Name',
          placeholder: 'Account holder name',
          required: true,
          templateVariable: 'repayment_account_name',
        },
        {
          id: 'repaymentAccountNumber',
          name: 'repayment.accountNumber',
          type: 'text',
          label: 'Repayment Account Number',
          placeholder: 'Enter 10-digit account number',
          required: true,
          validation: {
            pattern: '^[0-9]{10}$',
            patternMessage: 'Account number must be exactly 10 digits',
          },
          templateVariable: 'repayment_account_number',
        },
      ],
    },

    // Step 11: Supporting Documents
    {
      id: 'documents',
      title: 'Supporting Documents',
      description: 'Upload required documents',
      fields: [
        {
          id: 'passportCopy',
          name: 'documents.passportCopy',
          type: 'file',
          label: 'International Passport Data Page',
          helpText: 'Upload a clear scan or photo of your passport data page',
          required: true,
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
        },
        {
          id: 'ninSlip',
          name: 'documents.ninSlip',
          type: 'file',
          label: 'NIN Slip or National ID',
          helpText: 'Upload your NIN slip or National ID card',
          required: true,
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
        },
        {
          id: 'admissionLetter',
          name: 'documents.admissionLetter',
          type: 'file',
          label: 'Admission Letter',
          helpText: 'Upload your admission/offer letter from the institution',
          required: true,
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
          showIf: {
            field: 'visa.type',
            operator: 'equals',
            value: 'student',
          },
        },
        {
          id: 'employmentLetter',
          name: 'documents.employmentLetter',
          type: 'file',
          label: 'Employment/Job Offer Letter',
          helpText: 'Upload your employment or job offer letter',
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
          showIf: {
            field: 'visa.type',
            operator: 'equals',
            value: 'skilled_work',
          },
        },
        {
          id: 'lpoDocument',
          name: 'documents.lpoDocument',
          type: 'file',
          label: 'LPO / Contract Document',
          helpText: 'Upload the LPO or contract document',
          required: true,
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
          showIf: {
            field: 'loan.purpose',
            operator: 'equals',
            value: 'lpo_financing',
          },
        },
        {
          id: 'contractAwardLetter',
          name: 'documents.contractAwardLetter',
          type: 'file',
          label: 'Contract Award Letter',
          helpText: 'Upload the contract award letter if available',
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
          showIf: {
            field: 'loan.purpose',
            operator: 'equals',
            value: 'lpo_financing',
          },
        },
        {
          id: 'cacCertificate',
          name: 'documents.cacCertificate',
          type: 'file',
          label: 'CAC Certificate',
          helpText: 'Upload your company registration certificate',
          required: true,
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
          showIf: {
            field: 'applicant.category',
            operator: 'equals',
            value: 'individual_corporate',
          },
        },
        {
          id: 'proofOfAddress',
          name: 'documents.proofOfAddress',
          type: 'file',
          label: 'Proof of Address',
          helpText: 'Utility bill or bank statement (not older than 3 months)',
          accept: '.pdf,.jpg,.jpeg,.png',
          maxSize: 5242880,
        },
      ],
    },

    // Step 12: Terms Acknowledgement & Declaration
    {
      id: 'terms-acknowledgement',
      title: 'Terms & Declaration',
      description: 'Please read and accept the declarations and terms',
      sections: [
        {
          id: 'liability-section',
          title: 'Joint & Several Liability',
          fields: [
            {
              id: 'ackJointLiability',
              name: 'acknowledgements.jointLiability',
              type: 'checkbox',
              label:
                'All listed parties accept joint and several liability for Principal, Interest, Late fees, and Enforcement costs',
              required: true,
            },
          ],
        },
        {
          id: 'terms-section',
          title: 'Loan Terms',
          fields: [
            {
              id: 'ackInterestTerms',
              name: 'acknowledgements.interestTerms',
              type: 'checkbox',
              label: 'I acknowledge interest is non-refundable once principal is received',
              required: true,
            },
            {
              id: 'ackLateFees',
              name: 'acknowledgements.lateFees',
              type: 'checkbox',
              label: 'I acknowledge a late fee of 4% per day applies after the due date',
              required: true,
            },
            {
              id: 'ackRemedies',
              name: 'acknowledgements.remedies',
              type: 'checkbox',
              label: 'I understand the Lender may enforce remedies after the second week of default',
              required: true,
            },
            {
              id: 'ackRenewal',
              name: 'acknowledgements.renewal',
              type: 'checkbox',
              label:
                'I understand renewal request must be submitted 48 hours before expiry; failure to renew terminates the contract automatically',
              required: true,
            },
            {
              id: 'ackRepayment',
              name: 'acknowledgements.repayment',
              type: 'checkbox',
              label: 'I acknowledge repayment is non-negotiable and time-bound',
              required: true,
            },
          ],
        },
        {
          id: 'declaration-section',
          title: 'Legal Declaration',
          fields: [
            {
              id: 'declarationNotInfant',
              name: 'declaration.notInfant',
              type: 'checkbox',
              label: 'I declare that I am not an infant (I am 18 years or older)',
              required: true,
            },
            {
              id: 'declarationSoundMind',
              name: 'declaration.soundMind',
              type: 'checkbox',
              label: 'I declare that I am not a person of unsound mind',
              required: true,
            },
            {
              id: 'declarationNoFraud',
              name: 'declaration.noFraud',
              type: 'checkbox',
              label:
                'I declare that I have not been convicted of any offence involving fraud or dishonesty within five years of this loan application',
              required: true,
            },
            {
              id: 'declarationNotBankrupt',
              name: 'declaration.notBankrupt',
              type: 'checkbox',
              label: 'I declare that I am not an undischarged bankrupt',
              required: true,
            },
            {
              id: 'declarationGoodFaith',
              name: 'declaration.goodFaith',
              type: 'checkbox',
              label:
                'I make this declaration in good faith, believing the same to be true and in accordance with the Oaths Act, 1990',
              required: true,
            },
          ],
        },
      ],
    },
  ],
};

export default proofOfFundsSchema;
