import type { FormSchema } from '@/types/form-schema.types';

export const studentPofSchema: FormSchema = {
  id: 'student-pof',
  version: 1,
  title: 'Student Proof of Funds - Loan Agreement',
  description: 'Complete this form to generate a loan agreement for student visa proof of funds',
  validation: {
    validateOnBlur: true,
    validateOnChange: false,
    showErrorsOnSubmit: true,
  },
  steps: [
    // Step 1: Document Metadata
    {
      id: 'metadata',
      title: 'Document Metadata',
      description: 'Enter the loan agreement document details',
      fields: [
        {
          id: 'documentTitle',
          name: 'metadata.documentTitle',
          type: 'text',
          label: 'Document Title',
          defaultValue: 'LOAN AGREEMENT',
          readonly: true,
          templateVariable: 'document_title',
        },
        {
          id: 'agreementType',
          name: 'metadata.agreementType',
          type: 'text',
          label: 'Agreement Type',
          placeholder: 'e.g., Personal Loan Agreement',
          defaultValue: 'Personal Loan Agreement',
          templateVariable: 'agreement_type',
        },
        {
          id: 'referenceNumber',
          name: 'metadata.referenceNumber',
          type: 'text',
          label: 'Reference Number',
          placeholder: 'e.g., Ref/Loan/18/12/2025',
          required: true,
          templateVariable: 'reference_number',
        },
        {
          id: 'effectiveDate',
          name: 'metadata.effectiveDate',
          type: 'date',
          label: 'Effective Date',
          required: true,
          templateVariable: 'effective_date',
        },
      ],
    },

    // Step 2: Parties
    {
      id: 'parties',
      title: 'Parties',
      description: 'Enter details for all parties involved in the loan agreement',
      sections: [
        // Party A - Lender
        {
          id: 'lender',
          title: 'Party A — Lender',
          fields: [
            {
              id: 'lenderFullName',
              name: 'lender.fullName',
              type: 'text',
              label: 'Lender Full Name',
              placeholder: 'Enter lender full legal name',
              required: true,
              templateVariable: 'lender_name',
            },
            {
              id: 'lenderAddress',
              name: 'lender.address',
              type: 'textarea',
              label: 'Lender Address',
              placeholder: 'Enter complete address',
              required: true,
              rows: 2,
              templateVariable: 'lender_address',
            },
          ],
        },
        // Party B - Borrower
        {
          id: 'borrower',
          title: 'Party B — Borrower',
          fields: [
            {
              id: 'borrowerFullName',
              name: 'borrower.fullName',
              type: 'text',
              label: 'Borrower Full Name',
              placeholder: 'Enter borrower full legal name',
              required: true,
              templateVariable: 'borrower_name',
            },
            {
              id: 'borrowerAddress',
              name: 'borrower.address',
              type: 'textarea',
              label: 'Borrower Address',
              placeholder: 'Enter complete residential address',
              required: true,
              rows: 2,
              templateVariable: 'borrower_address',
            },
            {
              id: 'borrowerPassport',
              name: 'borrower.passportNumber',
              type: 'text',
              label: 'International Passport Number',
              placeholder: 'e.g., A12345678',
              templateVariable: 'borrower_passport',
            },
            {
              id: 'borrowerNIN',
              name: 'borrower.nin',
              type: 'text',
              label: 'NIN (National Identification Number)',
              placeholder: 'Enter 11-digit NIN',
              validation: {
                pattern: '^[0-9]{11}$',
                patternMessage: 'NIN must be exactly 11 digits',
              },
              templateVariable: 'borrower_nin',
            },
            {
              id: 'borrowerPhone',
              name: 'borrower.phone',
              type: 'phone',
              label: 'Mobile Number',
              placeholder: '08012345678',
              required: true,
              templateVariable: 'borrower_phone',
            },
          ],
        },
        // Party C - Agent
        {
          id: 'agent',
          title: 'Party C — Agent',
          fields: [
            {
              id: 'agentFullName',
              name: 'agent.fullName',
              type: 'text',
              label: 'Agent Full Name',
              placeholder: 'Enter agent full name',
              templateVariable: 'agent_name',
            },
            {
              id: 'agentAddress',
              name: 'agent.address',
              type: 'textarea',
              label: 'Agent Address',
              placeholder: 'Enter agent address',
              rows: 2,
              templateVariable: 'agent_address',
            },
            {
              id: 'agentNIN',
              name: 'agent.nin',
              type: 'text',
              label: 'Agent NIN',
              placeholder: 'Enter 11-digit NIN',
              validation: {
                pattern: '^[0-9]{11}$',
                patternMessage: 'NIN must be exactly 11 digits',
              },
              templateVariable: 'agent_nin',
            },
            {
              id: 'agentPhone',
              name: 'agent.phone',
              type: 'phone',
              label: 'Agent Mobile Number',
              placeholder: '08012345678',
              templateVariable: 'agent_phone',
            },
          ],
        },
      ],
    },

    // Step 3: Loan Details
    {
      id: 'loan-details',
      title: 'Loan Details',
      description: 'Enter the loan recitals, principal amount, duration, and repayment details',
      sections: [
        // Recitals
        {
          id: 'recitals',
          title: 'Recitals (Purpose of Loan)',
          fields: [
            {
              id: 'studentFullName',
              name: 'recitals.studentFullName',
              type: 'text',
              label: 'Student/Beneficiary Full Name',
              placeholder: 'Enter student full name as on passport',
              required: true,
              templateVariable: 'student_name',
            },
            {
              id: 'admissionStudentId',
              name: 'recitals.studentId',
              type: 'text',
              label: 'Admission Letter Student ID',
              placeholder: 'Enter student ID from admission letter',
              templateVariable: 'student_id',
            },
            {
              id: 'institutionName',
              name: 'recitals.institutionName',
              type: 'text',
              label: 'Institution Name',
              placeholder: 'e.g., University of Toronto',
              required: true,
              templateVariable: 'institution_name',
            },
            {
              id: 'program',
              name: 'recitals.program',
              type: 'text',
              label: 'Program',
              placeholder: 'e.g., Bachelor of Computer Science',
              templateVariable: 'program',
            },
            {
              id: 'session',
              name: 'recitals.session',
              type: 'text',
              label: 'Session',
              placeholder: 'e.g., 2025/2026',
              templateVariable: 'session',
            },
            {
              id: 'studyLoad',
              name: 'recitals.studyLoad',
              type: 'select',
              label: 'Study Load',
              options: [
                { value: 'full_time', label: 'Full Time' },
                { value: 'part_time', label: 'Part Time' },
              ],
              templateVariable: 'study_load',
            },
            {
              id: 'purposeOfLoan',
              name: 'recitals.purposeOfLoan',
              type: 'textarea',
              label: 'Purpose of Loan',
              placeholder: 'e.g., to provide proof of funds for student visa application...',
              required: true,
              rows: 3,
              defaultValue: 'to provide proof of funds for student visa application to support the beneficiary\'s study abroad',
              templateVariable: 'loan_purpose',
            },
          ],
        },
        // Principal Amount
        {
          id: 'principal',
          title: 'Principal / Loan Amount',
          fields: [
            {
              id: 'principalAmount',
              name: 'principal.amount',
              type: 'currency',
              label: 'Principal Amount',
              placeholder: 'Enter loan amount',
              required: true,
              helpText: 'Enter the total principal loan amount',
              validation: {
                min: 1000000,
              },
              templateVariable: 'principal_amount',
            },
            {
              id: 'currency',
              name: 'principal.currency',
              type: 'select',
              label: 'Currency',
              required: true,
              defaultValue: 'NGN',
              options: [
                { value: 'NGN', label: 'Nigerian Naira (NGN)' },
                { value: 'USD', label: 'US Dollar (USD)' },
                { value: 'GBP', label: 'British Pound (GBP)' },
                { value: 'EUR', label: 'Euro (EUR)' },
                { value: 'CAD', label: 'Canadian Dollar (CAD)' },
              ],
              templateVariable: 'currency',
            },
            {
              id: 'amountInWords',
              name: 'principal.amountInWords',
              type: 'text',
              label: 'Amount in Words',
              placeholder: 'e.g., Seven Million Naira only',
              required: true,
              helpText: 'Write out the amount in words',
              templateVariable: 'amount_in_words',
            },
            {
              id: 'disbursementMethod',
              name: 'principal.disbursementMethod',
              type: 'select',
              label: 'Disbursement Method',
              required: true,
              defaultValue: 'bank_transfer',
              options: [
                { value: 'bank_transfer', label: 'Bank Transfer' },
                { value: 'cash', label: 'Cash' },
                { value: 'other', label: 'Other' },
              ],
              templateVariable: 'disbursement_method',
            },
            {
              id: 'fromLenderBank',
              name: 'principal.fromLenderBank',
              type: 'text',
              label: 'From (Lender) Bank Name',
              placeholder: 'Enter lender bank name',
              templateVariable: 'lender_bank',
            },
            {
              id: 'fromLenderAccount',
              name: 'principal.fromLenderAccount',
              type: 'text',
              label: 'From (Lender) Account Number',
              placeholder: 'Enter lender account number',
              templateVariable: 'lender_account',
            },
            {
              id: 'toBorrowerAccountName',
              name: 'principal.toBorrowerAccountName',
              type: 'text',
              label: 'To (Borrower) Account Name',
              placeholder: 'Account holder name',
              required: true,
              templateVariable: 'borrower_account_name',
            },
            {
              id: 'toBorrowerBank',
              name: 'principal.toBorrowerBank',
              type: 'text',
              label: 'To (Borrower) Bank Name',
              placeholder: 'e.g., First Bank',
              required: true,
              templateVariable: 'borrower_bank',
            },
            {
              id: 'toBorrowerAccount',
              name: 'principal.toBorrowerAccount',
              type: 'text',
              label: 'To (Borrower) Account Number',
              placeholder: 'Enter 10-digit account number',
              required: true,
              validation: {
                pattern: '^[0-9]{10}$',
                patternMessage: 'Account number must be exactly 10 digits',
              },
              templateVariable: 'borrower_account_number',
            },
          ],
        },
        // Duration
        {
          id: 'duration',
          title: 'Duration',
          fields: [
            {
              id: 'loanStartDate',
              name: 'duration.startDate',
              type: 'date',
              label: 'Loan Start Date',
              required: true,
              templateVariable: 'loan_start_date',
            },
            {
              id: 'loanEndDate',
              name: 'duration.endDate',
              type: 'date',
              label: 'Loan End Date',
              required: true,
              templateVariable: 'loan_end_date',
            },
          ],
        },
        // Repayment
        {
          id: 'repayment',
          title: 'Repayment',
          fields: [
            {
              id: 'repaymentType',
              name: 'repayment.type',
              type: 'radio',
              label: 'Repayment Type',
              required: true,
              defaultValue: 'lump_sum',
              options: [
                {
                  value: 'lump_sum',
                  label: 'Lump Sum',
                  description: 'Single payment at end of term',
                },
                {
                  value: 'installments',
                  label: 'Installments',
                  description: 'Multiple payments over time',
                },
              ],
              templateVariable: 'repayment_type',
            },
            // Lump Sum fields
            {
              id: 'repaymentDueDate',
              name: 'repayment.dueDate',
              type: 'date',
              label: 'Repayment Due Date',
              required: true,
              showIf: {
                field: 'repayment.type',
                operator: 'equals',
                value: 'lump_sum',
              },
              templateVariable: 'repayment_due_date',
            },
            // Installment fields
            {
              id: 'numberOfInstallments',
              name: 'repayment.numberOfInstallments',
              type: 'number',
              label: 'Number of Installments',
              placeholder: 'e.g., 12',
              showIf: {
                field: 'repayment.type',
                operator: 'equals',
                value: 'installments',
              },
              templateVariable: 'num_installments',
            },
            {
              id: 'installmentAmount',
              name: 'repayment.installmentAmount',
              type: 'currency',
              label: 'Installment Amount',
              placeholder: 'Enter amount per installment',
              showIf: {
                field: 'repayment.type',
                operator: 'equals',
                value: 'installments',
              },
              templateVariable: 'installment_amount',
            },
            {
              id: 'installmentSchedule',
              name: 'repayment.installmentSchedule',
              type: 'select',
              label: 'Installment Schedule',
              options: [
                { value: 'weekly', label: 'Weekly' },
                { value: 'bi_weekly', label: 'Bi-Weekly' },
                { value: 'monthly', label: 'Monthly' },
                { value: 'quarterly', label: 'Quarterly' },
              ],
              showIf: {
                field: 'repayment.type',
                operator: 'equals',
                value: 'installments',
              },
              templateVariable: 'installment_schedule',
            },
            {
              id: 'firstPaymentDate',
              name: 'repayment.firstPaymentDate',
              type: 'date',
              label: 'First Payment Date',
              showIf: {
                field: 'repayment.type',
                operator: 'equals',
                value: 'installments',
              },
              templateVariable: 'first_payment_date',
            },
            // Destination account (for both types)
            {
              id: 'repaymentAccountName',
              name: 'repayment.accountName',
              type: 'text',
              label: 'Repayment Destination Account Name',
              placeholder: 'Account holder name',
              required: true,
              templateVariable: 'repayment_account_name',
            },
            {
              id: 'repaymentBankName',
              name: 'repayment.bankName',
              type: 'text',
              label: 'Repayment Destination Bank Name',
              placeholder: 'e.g., First Bank',
              required: true,
              templateVariable: 'repayment_bank',
            },
            {
              id: 'repaymentAccountNumber',
              name: 'repayment.accountNumber',
              type: 'text',
              label: 'Repayment Destination Account Number',
              placeholder: 'Enter 10-digit account number',
              required: true,
              validation: {
                pattern: '^[0-9]{10}$',
                patternMessage: 'Account number must be exactly 10 digits',
              },
              templateVariable: 'repayment_account_number',
            },
          ],
        },
      ],
    },

    // Step 4: Terms
    {
      id: 'terms',
      title: 'Terms',
      description: 'Configure interest, renewal, late fees, and legal clauses',
      sections: [
        // Interest
        {
          id: 'interest',
          title: 'Interest',
          fields: [
            {
              id: 'interestApplies',
              name: 'interest.applies',
              type: 'checkbox',
              label: 'Interest Applies?',
              defaultValue: true,
              templateVariable: 'interest_applies',
            },
            {
              id: 'interestType',
              name: 'interest.type',
              type: 'select',
              label: 'Interest Type',
              defaultValue: 'flat',
              options: [
                { value: 'flat', label: 'Flat Rate' },
                { value: 'monthly', label: 'Monthly %' },
                { value: 'annual', label: 'Annual %' },
              ],
              showIf: {
                field: 'interest.applies',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'interest_type',
            },
            {
              id: 'interestRate',
              name: 'interest.rate',
              type: 'number',
              label: 'Interest Rate (%)',
              placeholder: 'e.g., 5',
              showIf: {
                field: 'interest.applies',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'interest_rate',
            },
            {
              id: 'interestNotes',
              name: 'interest.notes',
              type: 'textarea',
              label: 'Interest Notes',
              placeholder: 'Any additional notes about interest terms',
              rows: 2,
              showIf: {
                field: 'interest.applies',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'interest_notes',
            },
            {
              id: 'interestClauseText',
              name: 'interest.clauseText',
              type: 'textarea',
              label: 'Interest Clause Text (if no interest)',
              placeholder: 'Enter clause text for zero-interest agreement',
              rows: 2,
              showIf: {
                field: 'interest.applies',
                operator: 'equals',
                value: false,
              },
              templateVariable: 'no_interest_clause',
            },
          ],
        },
        // Renewal
        {
          id: 'renewal',
          title: 'Renewal',
          fields: [
            {
              id: 'renewalAllowed',
              name: 'renewal.allowed',
              type: 'checkbox',
              label: 'Renewal Allowed?',
              defaultValue: true,
              templateVariable: 'renewal_allowed',
            },
            {
              id: 'renewalHours',
              name: 'renewal.hoursBeforeExpiry',
              type: 'number',
              label: 'Renewal Condition (Hours Before Expiry)',
              placeholder: '48',
              defaultValue: 48,
              showIf: {
                field: 'renewal.allowed',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'renewal_hours',
            },
            {
              id: 'renewalNotes',
              name: 'renewal.notes',
              type: 'textarea',
              label: 'Renewal Notes',
              placeholder: 'Any additional notes about renewal terms',
              rows: 2,
              showIf: {
                field: 'renewal.allowed',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'renewal_notes',
            },
          ],
        },
        // Late Fee
        {
          id: 'lateFee',
          title: 'Late Fee',
          fields: [
            {
              id: 'lateFeeApplies',
              name: 'lateFee.applies',
              type: 'checkbox',
              label: 'Late Fee Applies?',
              defaultValue: true,
              templateVariable: 'late_fee_applies',
            },
            {
              id: 'lateFeeRate',
              name: 'lateFee.rate',
              type: 'number',
              label: 'Late Fee Rate (%)',
              placeholder: '4',
              defaultValue: 4,
              showIf: {
                field: 'lateFee.applies',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'late_fee_rate',
            },
            {
              id: 'lateFeeTrigger',
              name: 'lateFee.trigger',
              type: 'text',
              label: 'Late Fee Trigger',
              placeholder: 'e.g., if payment not effected on due date',
              defaultValue: 'if payment is not effected on due date',
              showIf: {
                field: 'lateFee.applies',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'late_fee_trigger',
            },
            {
              id: 'extraRuleWeeks',
              name: 'lateFee.extraRuleWeeks',
              type: 'number',
              label: 'Extra Rule After X Weeks Late',
              placeholder: '2',
              defaultValue: 2,
              helpText: 'Number of weeks after which additional remedies can be enforced',
              showIf: {
                field: 'lateFee.applies',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'late_fee_weeks',
            },
            {
              id: 'lateFeeNotes',
              name: 'lateFee.notes',
              type: 'textarea',
              label: 'Late Fee Notes',
              placeholder: 'Any additional notes about late fee terms',
              rows: 2,
              showIf: {
                field: 'lateFee.applies',
                operator: 'equals',
                value: true,
              },
              templateVariable: 'late_fee_notes',
            },
          ],
        },
        // Clauses
        {
          id: 'clauses',
          title: 'Other Clauses',
          description: 'Toggle which standard clauses to include in the agreement',
          fields: [
            {
              id: 'encumbranceClause',
              name: 'clauses.encumbrance',
              type: 'checkbox',
              label: 'Encumbrance Clause Included',
              defaultValue: true,
              templateVariable: 'clause_encumbrance',
            },
            {
              id: 'remediesClause',
              name: 'clauses.remedies',
              type: 'checkbox',
              label: 'Remedies Clause Included',
              defaultValue: true,
              templateVariable: 'clause_remedies',
            },
            {
              id: 'accelerationClause',
              name: 'clauses.acceleration',
              type: 'checkbox',
              label: 'Event of Acceleration Clause Included',
              defaultValue: true,
              templateVariable: 'clause_acceleration',
            },
            {
              id: 'expensesClause',
              name: 'clauses.expenses',
              type: 'checkbox',
              label: 'Expenses Clause Included',
              defaultValue: true,
              templateVariable: 'clause_expenses',
            },
            {
              id: 'waiverClause',
              name: 'clauses.waiver',
              type: 'checkbox',
              label: 'Waiver by Borrowers Clause Included',
              defaultValue: true,
              templateVariable: 'clause_waiver',
            },
            {
              id: 'successorsClause',
              name: 'clauses.successors',
              type: 'checkbox',
              label: 'Successors Clause Included',
              defaultValue: true,
              templateVariable: 'clause_successors',
            },
            {
              id: 'governingLaw',
              name: 'clauses.governingLaw',
              type: 'text',
              label: 'Governing Law',
              defaultValue: 'Federal Republic of Nigeria',
              templateVariable: 'governing_law',
            },
            {
              id: 'amendmentsClause',
              name: 'clauses.amendments',
              type: 'checkbox',
              label: 'Amendments Clause Included',
              defaultValue: true,
              templateVariable: 'clause_amendments',
            },
            {
              id: 'entireAgreementClause',
              name: 'clauses.entireAgreement',
              type: 'checkbox',
              label: 'Entire Agreement Clause Included',
              defaultValue: true,
              templateVariable: 'clause_entire_agreement',
            },
          ],
        },
      ],
    },

    // Step 5: Signatures
    {
      id: 'signatures',
      title: 'Signatures',
      description: 'Enter signature details for all parties',
      sections: [
        // Lender Signature
        {
          id: 'lenderSignature',
          title: 'Lender Signature',
          fields: [
            {
              id: 'lenderSigName',
              name: 'signatures.lender.name',
              type: 'text',
              label: 'Lender Signature Name',
              placeholder: 'Enter name as it will appear on signature',
              required: true,
              templateVariable: 'lender_sig_name',
            },
            {
              id: 'lenderSigDate',
              name: 'signatures.lender.date',
              type: 'date',
              label: 'Lender Signature Date',
              required: true,
              templateVariable: 'lender_sig_date',
            },
            {
              id: 'lenderWitnessName',
              name: 'signatures.lender.witnessName',
              type: 'text',
              label: 'Lender Witness Name',
              placeholder: 'Enter witness name',
              templateVariable: 'lender_witness_name',
            },
            {
              id: 'lenderWitnessDate',
              name: 'signatures.lender.witnessDate',
              type: 'date',
              label: 'Lender Witness Signature Date',
              templateVariable: 'lender_witness_date',
            },
          ],
        },
        // Borrower Signature
        {
          id: 'borrowerSignature',
          title: 'Borrower Signature',
          fields: [
            {
              id: 'borrowerSigName',
              name: 'signatures.borrower.name',
              type: 'text',
              label: 'Borrower Signature Name',
              placeholder: 'Enter name as it will appear on signature',
              required: true,
              templateVariable: 'borrower_sig_name',
            },
            {
              id: 'borrowerSigDate',
              name: 'signatures.borrower.date',
              type: 'date',
              label: 'Borrower Signature Date',
              required: true,
              templateVariable: 'borrower_sig_date',
            },
            {
              id: 'borrowerNOKName',
              name: 'signatures.borrower.nokName',
              type: 'text',
              label: 'Borrower NOK/Witness Name',
              placeholder: 'Enter next of kin or witness name',
              templateVariable: 'borrower_nok_name',
            },
            {
              id: 'borrowerNOKDate',
              name: 'signatures.borrower.nokDate',
              type: 'date',
              label: 'Borrower NOK/Witness Date',
              templateVariable: 'borrower_nok_date',
            },
          ],
        },
        // Agent Signature
        {
          id: 'agentSignature',
          title: 'Agent Signature',
          fields: [
            {
              id: 'agentSigName',
              name: 'signatures.agent.name',
              type: 'text',
              label: 'Agent Signature Name',
              placeholder: 'Enter name as it will appear on signature',
              templateVariable: 'agent_sig_name',
            },
            {
              id: 'agentSigDate',
              name: 'signatures.agent.date',
              type: 'date',
              label: 'Agent Signature Date',
              templateVariable: 'agent_sig_date',
            },
          ],
        },
      ],
    },

    // Step 6: Declaration Form
    {
      id: 'declaration',
      title: 'Declaration Form',
      description: 'Complete the legal declaration',
      sections: [
        // Header
        {
          id: 'declarationHeader',
          title: 'Declaration Header',
          fields: [
            {
              id: 'declarationTitle',
              name: 'declaration.title',
              type: 'text',
              label: 'Declaration Title',
              defaultValue: 'DECLARATION FORM',
              readonly: true,
              templateVariable: 'declaration_title',
            },
            {
              id: 'linkedAgreementTitle',
              name: 'declaration.linkedAgreementTitle',
              type: 'text',
              label: 'Linked Agreement Title',
              defaultValue: 'Personal Loan Agreement',
              templateVariable: 'linked_agreement',
            },
            {
              id: 'declarationRefNumber',
              name: 'declaration.referenceNumber',
              type: 'text',
              label: 'Declaration Reference Number',
              placeholder: 'Enter reference number',
              required: true,
              templateVariable: 'declaration_ref',
            },
          ],
        },
        // Declarant Identity
        {
          id: 'declarantIdentity',
          title: 'Declarant Identity',
          fields: [
            {
              id: 'declarantFullNames',
              name: 'declaration.declarantFullNames',
              type: 'text',
              label: 'Declarant Full Names',
              placeholder: 'Enter full legal names',
              required: true,
              templateVariable: 'declarant_names',
            },
            {
              id: 'declarantAddress',
              name: 'declaration.declarantAddress',
              type: 'textarea',
              label: 'Declarant Address',
              placeholder: 'Enter complete address',
              required: true,
              rows: 2,
              templateVariable: 'declarant_address',
            },
            {
              id: 'addressType',
              name: 'declaration.addressType',
              type: 'select',
              label: 'Address Type',
              options: [
                { value: 'permanent', label: 'Permanent Address' },
                { value: 'school', label: 'School Address' },
                { value: 'other', label: 'Other' },
              ],
              templateVariable: 'address_type',
            },
          ],
        },
        // Declaration Statements
        {
          id: 'declarationStatements',
          title: 'Declaration Statements',
          description: 'Please confirm each of the following declarations',
          fields: [
            {
              id: 'notInfant',
              name: 'declaration.notInfant',
              type: 'checkbox',
              label: 'I am not an infant (I am 18 years or older)',
              required: true,
              templateVariable: 'decl_not_infant',
            },
            {
              id: 'soundMind',
              name: 'declaration.soundMind',
              type: 'checkbox',
              label: 'I am not a person of unsound mind',
              required: true,
              templateVariable: 'decl_sound_mind',
            },
            {
              id: 'noFraud',
              name: 'declaration.noFraud',
              type: 'checkbox',
              label: 'I have not been convicted of any offence involving fraud or dishonesty within five years of this declaration',
              required: true,
              templateVariable: 'decl_no_fraud',
            },
            {
              id: 'notBankrupt',
              name: 'declaration.notBankrupt',
              type: 'checkbox',
              label: 'I am not an undischarged bankrupt',
              required: true,
              templateVariable: 'decl_not_bankrupt',
            },
            {
              id: 'goodFaith',
              name: 'declaration.goodFaith',
              type: 'checkbox',
              label: 'I make this declaration in good faith, believing the same to be true and in accordance with the Oaths Act, 1990',
              required: true,
              templateVariable: 'decl_good_faith',
            },
          ],
        },
        // Execution Date
        {
          id: 'executionDate',
          title: 'Execution Date',
          fields: [
            {
              id: 'declarationDate',
              name: 'declaration.date',
              type: 'date',
              label: 'Declaration Date',
              required: true,
              templateVariable: 'declaration_date',
            },
          ],
        },
      ],
    },
  ],
};

export default studentPofSchema;
